### PR TITLE
Add note about mentioning clients in issues

### PR DESCRIPTION
**Pull request by alexbirkett**

### CODE REVIEW

**Comment by aarsland** [comment]
Er should also have a receipt of what to do if someone forgets. How can we delete a commit that contains any secrets.

**Comment by alexbirkett** [comment]
See [Pr 5](https://github.com/agensdev/playbook/pull/5) @aarsland

**Comment by kostiakoval** [comment]
Is some ones mention clients in issue, you can always edit the issue!

**Comment by hfossli** [comment]
Not if it is checked in to git in our markdowns ;)

**Pull request merged**
